# Generated by Django 6.0 on 2026-01-17 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audit_enabled', models.BooleanField(default=True, help_text='When enabled, query events are logged to audit log')),
                ('audit_store_queries', models.BooleanField(default=False, help_text='When enabled, raw SQL queries are stored in audit logs')),
                ('allowed_email_domains', models.JSONField(default=list, help_text='List of email domains that can join without an invite code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.workspace')),
            ],
            options={
                'verbose_name_plural': 'workspace settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_type', models.CharField(choices=[('user', 'USER'), ('system', 'SYSTEM'), ('api_key', 'API_KEY')], max_length=20)),
                ('actor_id', models.UUIDField(blank=True, help_text='User ID when actor_type=USER', null=True)),
                ('actor_email', models.CharField(blank=True, help_text='Denormalized for CSV export', max_length=255, null=True)),
                ('event_type', models.CharField(choices=[('query.execute', 'QUERY_EXECUTE'), ('query.cancel', 'QUERY_CANCEL'), ('user.joined', 'USER_JOINED'), ('account.access.requested', 'ACCOUNT_ACCESS_REQUESTED'), ('account.access.granted', 'ACCOUNT_ACCESS_GRANTED'), ('account.access.denied', 'ACCOUNT_ACCESS_DENIED'), ('account.access.revoked', 'ACCOUNT_ACCESS_REVOKED')], max_length=50)),
                ('database_id', models.UUIDField(blank=True, null=True)),
                ('database_name', models.CharField(blank=True, help_text='Denormalized', max_length=200, null=True)),
                ('query_actor_type', models.CharField(blank=True, choices=[('application', 'APPLICATION'), ('user', 'USER'), ('custom', 'CUSTOM')], max_length=20, null=True)),
                ('query_hash', models.CharField(blank=True, help_text='SHA256 of query text', max_length=64, null=True)),
                ('query_text', models.TextField(blank=True, help_text='Only stored if workspace.audit_store_queries=True', null=True)),
                ('database', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='workspace_a_workspa_a120b5_idx'), models.Index(fields=['workspace', 'event_type'], name='workspace_a_workspa_67bf4e_idx'), models.Index(fields=['workspace', 'actor_id'], name='workspace_a_workspa_9c1b4e_idx')],
            },
        ),
    ]
