# Generated by Django 6.0 on 2026-01-17 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('new_key', 'NEW_KEY'), ('access_requested', 'ACCESS_REQUESTED'), ('access_approved', 'ACCESS_APPROVED'), ('access_denied', 'ACCESS_DENIED')], help_text='Type of notification', max_length=50)),
                ('event_id', models.CharField(db_index=True, help_text='Event identifier for deduplication (multiple notifications can share same event_id)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queued_at', models.DateTimeField(blank=True, help_text='When notification was queued for dispatch', null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, help_text='When notification was dispatched (any channel)', null=True)),
                ('slack_dispatched_at', models.DateTimeField(blank=True, help_text='When notification was dispatched via Slack', null=True)),
                ('email_dispatched_at', models.DateTimeField(blank=True, help_text='When notification was dispatched via email', null=True)),
                ('text_title', models.CharField(blank=True, help_text='Title/heading for the notification', max_length=255, null=True)),
                ('text_short', models.CharField(blank=True, help_text='Short summary text', max_length=500, null=True)),
                ('text_markdown', models.TextField(blank=True, help_text='Full markdown-formatted content', null=True)),
                ('text_slack', models.TextField(blank=True, help_text='Slack-formatted content', null=True)),
                ('cta_email', models.JSONField(blank=True, default=list, help_text='List of email CTAs (each with label, primary, url)', null=True)),
                ('cta_web', models.JSONField(blank=True, default=list, help_text='List of web/in-app CTAs (each with label, primary, url)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data for the notification', null=True)),
                ('skip_inbox', models.BooleanField(default=False, help_text="If True, notification won't appear in transactional inbox")),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Workspace this notification belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'recipient', 'created_at'], name='notificatio_workspa_aa9963_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['event_id'], name='notificatio_event_i_1afed9_idx'), models.Index(fields=['type', 'created_at'], name='notificatio_type_8e213d_idx')],
            },
        ),
    ]
