# Generated by Django 6.0 on 2026-01-17 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('connection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=0, help_text='Order position for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database', models.ForeignKey(blank=True, help_text='Database this folder is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='connection.database')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent folder (for future nested folders)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workbench.folder')),
                ('user', models.ForeignKey(help_text='Owner of this folder', on_delete=django.db.models.deletion.CASCADE, related_name='workbench_folders', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Workspace this folder belongs to (denormalized from user)', on_delete=django.db.models.deletion.CASCADE, related_name='workbench_folders', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, default='', help_text='SQL content')),
                ('position', models.IntegerField(default=0, help_text='Order position within folder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database', models.ForeignKey(blank=True, help_text='Database this worksheet is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to='connection.database')),
                ('folder', models.ForeignKey(blank=True, help_text='Containing folder (null = root level)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheets', to='workbench.folder')),
                ('user', models.ForeignKey(help_text='Owner of this worksheet', on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Workspace this worksheet belongs to (denormalized from user)', on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorksheetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Snapshot of worksheet content')),
                ('version_number', models.IntegerField(help_text='Incrementing version number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workbench.worksheet')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['workspace', 'user'], name='workbench_f_workspa_f0998f_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['user', 'database', 'position'], name='workbench_f_user_id_e7b789_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['database'], name='workbench_f_databas_70445e_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent'], name='workbench_f_parent__ee8ac3_idx'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('workspace', 'user', 'database', 'name'), name='workbench_folder_unique_name_per_database'),
        ),
        migrations.AddIndex(
            model_name='worksheet',
            index=models.Index(fields=['workspace', 'user'], name='workbench_w_workspa_5a145f_idx'),
        ),
        migrations.AddIndex(
            model_name='worksheet',
            index=models.Index(fields=['user', 'database', 'folder', 'position'], name='workbench_w_user_id_bee172_idx'),
        ),
        migrations.AddIndex(
            model_name='worksheet',
            index=models.Index(fields=['database'], name='workbench_w_databas_34f13a_idx'),
        ),
        migrations.AddIndex(
            model_name='worksheet',
            index=models.Index(fields=['folder'], name='workbench_w_folder__46cf96_idx'),
        ),
        migrations.AddConstraint(
            model_name='worksheet',
            constraint=models.UniqueConstraint(fields=('workspace', 'user', 'database', 'folder', 'name'), name='workbench_worksheet_unique_name_per_database_folder'),
        ),
        migrations.AddIndex(
            model_name='worksheetversion',
            index=models.Index(fields=['worksheet', 'created_at'], name='workbench_w_workshe_581ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='worksheetversion',
            index=models.Index(fields=['worksheet', 'version_number'], name='workbench_w_workshe_653988_idx'),
        ),
    ]
