"""
Django settings for vaultsql project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the repo root env.txt or a local .env
# env.txt is the canonical file; containers mount it as /app/.env
env_paths = [
    BASE_DIR.parent.parent / 'env.txt',
    BASE_DIR.parent / '.env',
    BASE_DIR.parent.parent / '.env',
]
for env_path in env_paths:
    if env_path.exists():
        load_dotenv(env_path)
        break


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def get_env(*keys, default=None, required=False):
    for key in keys:
        value = os.getenv(key)
        if value not in (None, ''):
            return value
    if required:
        raise ValueError(f"{keys[0]} environment variable must be set")
    return default


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env('API_SECRET_KEY', 'SECRET_KEY', required=True)

# Encryption key derived from SECRET_KEY for credential encryption
ENCRYPTION_KEY = get_env('API_ENCRYPTION_KEY', 'ENCRYPTION_KEY', default=SECRET_KEY)

# Query service secret for microservice authentication
QUERY_SERVICE_SECRET = get_env('QUERY_SERVICE_SECRET')

# Query service URL (Go microservice)
QUERY_SERVICE_URL = get_env(
    'APP_INTERNAL_QUERY',
    default='http://localhost:9000',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env('API_DEBUG', 'DEBUG', default='False').lower() in ('true', '1', 't')

# Allow hosts from environment or default to common Docker/localhost values
_allowed_hosts = get_env('API_ALLOWED_HOSTS', 'ALLOWED_HOSTS', default='')
if _allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',')]
else:
    # Default hosts for Docker and local development
    ALLOWED_HOSTS = [
        'localhost',
        'api',  # Docker service name
        'app.vaultsql.com',
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'corsheaders',
    'accounts',
    'connection',
    'django_celery_beat',
    'notifications',
    'workbench',
    'workspace',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vaultsql.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
            ],
        },
    },
]

WSGI_APPLICATION = 'vaultsql.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_env('API_DB_NAME', 'DB_NAME', default='django_db'),
        'USER': get_env('API_DB_USER', 'DB_USER', default='postgres'),
        'PASSWORD': get_env('API_DB_PASS', 'API_DB_PASSWORD', 'DB_PASS', 'DB_PASSWORD', default='postgres'),
        'HOST': get_env('API_DB_HOST', 'DB_HOST', default='localhost'),
        'PORT': get_env('API_DB_PORT', 'DB_PORT', default='5432'),
        'OPTIONS': {
            'sslmode': get_env('API_DB_SSLMODE', 'DB_SSLMODE', default='require'),
        },
    }
}
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Static files - minimal config for API-only
STATIC_URL = 'static/'


# Celery config
CELERY_BROKER_URL = get_env(
    'API_CELERY_BROKER_URL',
    'CELERY_BROKER_URL',
    default="redis://localhost:6379/0",
)
CELERY_RESULT_BACKEND = get_env(
    'API_CELERY_RESULT_BACKEND',
    'CELERY_RESULT_BACKEND',
    default="redis://localhost:6379/0",
)


CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://localhost:8400",  # Caddy dev proxy
    "https://app.vaultsql.io",
    "https://app.vaultsql.com",
]

CORS_ALLOW_CREDENTIALS = True

# Frontend URL for redirects (Stripe, OAuth, etc.)
# This should be the primary user-facing URL, not CORS origins
FRONTEND_URL = get_env('API_FRONTEND_URL', 'FRONTEND_URL', default='http://localhost:5173')

# Feature flags for optional 3rd-party integrations
ENABLE_GOOGLE_AUTH = get_env('ENABLE_GOOGLE_AUTH', default='false').lower() == 'true'
ENABLE_LOOPS = get_env('ENABLE_LOOPS', default='false').lower() == 'true'
ENABLE_R2 = get_env('ENABLE_R2', default='false').lower() == 'true'
ENABLE_S3 = get_env('ENABLE_S3', default='false').lower() == 'true'

if ENABLE_S3 and not ENABLE_R2:
    ENABLE_R2 = True

# OAuth configuration (only required when ENABLE_GOOGLE_AUTH=true)
if ENABLE_GOOGLE_AUTH:
    GOOGLE_CLIENT_ID = get_env('GOOGLE_CLIENT_ID', required=True)
    GOOGLE_CLIENT_SECRET = get_env('GOOGLE_CLIENT_SECRET', required=True)
    _google_redirects = get_env('GOOGLE_OAUTH_REDIRECT_URIS', default='')
    if _google_redirects:
        GOOGLE_OAUTH_REDIRECT_URIS = [uri.strip() for uri in _google_redirects.split(',') if uri.strip()]
    else:
        GOOGLE_OAUTH_REDIRECT_URIS = [
            f"{origin.rstrip('/')}/auth/complete/google" for origin in CORS_ALLOWED_ORIGINS
        ]
else:
    GOOGLE_CLIENT_ID = None
    GOOGLE_CLIENT_SECRET = None
    GOOGLE_OAUTH_REDIRECT_URIS = []

ENV_NAME = get_env('API_ENV_NAME', 'ENV_NAME', default='dev')

DEV_LOGIN_EMAIL = get_env('API_DEV_LOGIN_EMAIL', 'DEV_LOGIN_EMAIL', default='dev@vaultsql.com').strip().lower()
DEV_LOGIN_EMAIL_LOCALPART, _dev_login_sep, DEV_LOGIN_EMAIL_DOMAIN = DEV_LOGIN_EMAIL.partition('@')
if not _dev_login_sep or not DEV_LOGIN_EMAIL_LOCALPART or not DEV_LOGIN_EMAIL_DOMAIN:
    raise ValueError("DEV_LOGIN_EMAIL must be a valid email address")

# Custom user model
AUTH_USER_MODEL = 'accounts.User'


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Profile Health Sampling Rates
# Success requests are sampled at 10% (1 in 10)
PROFILE_HEALTH_SUCCESS_SAMPLE_RATE = float(
    get_env('PROFILE_HEALTH_SUCCESS_SAMPLE_RATE', default='0.1')
)
# Failure requests are sampled at 50% (1 in 2)
PROFILE_HEALTH_FAILURE_SAMPLE_RATE = float(
    get_env('PROFILE_HEALTH_FAILURE_SAMPLE_RATE', default='0.5')
)

IMAGE_MAX_DIMENSION = int(get_env('IMAGE_MAX_DIMENSION', default='512'))
IMAGE_WEBP_QUALITY = int(get_env('IMAGE_WEBP_QUALITY', default='85'))

# R2 Storage (Cloudflare) - only required when ENABLE_R2=true
if ENABLE_R2:
    R2_ACCESS_KEY = get_env('API_R2_ACCESS_KEY', required=True)
    R2_SECRET = get_env('API_R2_SECRET', required=True)
    R2_ENDPOINT = get_env('API_R2_ENDPOINT', required=True)
    R2_BUCKET = get_env('API_R2_BUCKET', required=True)
    R2_DOMAIN = get_env('API_R2_DOMAIN', required=True)
else:
    R2_ACCESS_KEY = None
    R2_SECRET = None
    R2_ENDPOINT = None
    R2_BUCKET = None
    R2_DOMAIN = None

# Loops.so Drip Mail Integration - only required when ENABLE_LOOPS=true
if ENABLE_LOOPS:
    LOOPS_API_TOKEN = get_env('API_LOOPS_KEY', required=True)
    LOOPS_MAILING_LISTS = {
        'create_workspace': 'cmkt9x76z0n9s0iym7mia2pk0',  # workspace owners
        'join_workspace': 'cmkt9x9me6qw50iyaas200lh1',    # workspace users
    }
else:
    LOOPS_API_TOKEN = ''
    LOOPS_MAILING_LISTS = {}
