# Generated by Django 6.0 on 2026-01-17 20:26

import accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'identities',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('mode', models.CharField(choices=[('vault', 'VAULT'), ('streamlined', 'STREAMLINED'), ('managed', 'MANAGED'), ('byok', 'BYOK')], default='streamlined', help_text='Vault: users manage keypairs. Streamlined: centralized credential management. BYOK: bring your own key', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'ADMIN'), ('member', 'MEMBER')], default='member', help_text="User's role in this workspace", max_length=20)),
                ('notification_read_at', models.DateTimeField(blank=True, help_text='Last time user opened notifications. Used to calculate unread count.', null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='When set, the user is deactivated in this workspace and cannot access it.', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('identity', models.ForeignKey(help_text='External identity (email, social login). Authentication happens here.', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.identity')),
                ('workspace', models.ForeignKey(help_text='Workspace this user belongs to. Each User is scoped to one workspace.', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.workspace')),
            ],
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'code'], name='accounts_lo_email_4be663_idx'), models.Index(fields=['expires_at'], name='accounts_lo_expires_53ed1e_idx'), models.Index(fields=['created_at'], name='accounts_lo_created_fec402_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'GOOGLE'), ('github', 'GITHUB'), ('microsoft', 'MICROSOFT')], max_length=20)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('role', models.CharField(blank=True, choices=[('admin', 'ADMIN'), ('member', 'MEMBER')], help_text='Denormalized from user.role for performance', max_length=20, null=True)),
                ('expiry', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(help_text='External identity associated with this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.identity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, help_text='Denormalized from user.workspace for performance', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('invalid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When set, invitation expires at this time', null=True)),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum number of times this invitation can be used', null=True)),
                ('use_count', models.IntegerField(default=0, help_text='Number of times this invitation has been used')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='InvitationUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_usages', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='accounts.workspaceinvitation')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.usergroup')),
            ],
            options={
                'indexes': [models.Index(fields=['group', 'user'], name='accounts_gr_group_i_3e0c4d_idx')],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='usergroup',
            index=models.Index(fields=['workspace', 'name'], name='accounts_us_workspa_e09d40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['provider', 'provider_user_id'], name='accounts_so_provide_71a274_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['workspace', 'user'], name='accounts_so_workspa_0354b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('workspace', 'provider', 'provider_user_id')},
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'token'], name='accounts_se_user_id_6ee47d_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['expiry'], name='accounts_se_expiry_7efd11_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['token'], name='accounts_pa_token_affdf2_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['expires_at'], name='accounts_pa_expires_01b447_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['workspace', 'user'], name='accounts_pa_workspa_7abd09_idx'),
        ),
        migrations.AddIndex(
            model_name='magiclink',
            index=models.Index(fields=['token'], name='accounts_ma_token_83fe32_idx'),
        ),
        migrations.AddIndex(
            model_name='magiclink',
            index=models.Index(fields=['expires_at'], name='accounts_ma_expires_fc1cec_idx'),
        ),
        migrations.AddIndex(
            model_name='magiclink',
            index=models.Index(fields=['workspace', 'user'], name='accounts_ma_workspa_426c05_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['workspace', 'email'], name='accounts_us_workspa_0c0c53_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['workspace', 'role'], name='accounts_us_workspa_0dfebd_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('workspace', 'email'), name='accounts_user_workspace_email_uniq'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('identity', 'workspace')},
        ),
        migrations.AddIndex(
            model_name='workspaceinvitation',
            index=models.Index(fields=['workspace', 'revoked_at'], name='accounts_wo_workspa_5313c9_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvitation',
            index=models.Index(fields=['token'], name='accounts_wo_token_782667_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvitation',
            index=models.Index(fields=['expires_at'], name='accounts_wo_expires_6fcf0c_idx'),
        ),
        migrations.AddIndex(
            model_name='invitationusage',
            index=models.Index(fields=['invitation', 'used_at'], name='accounts_in_invitat_17caf0_idx'),
        ),
        migrations.AddIndex(
            model_name='invitationusage',
            index=models.Index(fields=['user', 'used_at'], name='accounts_in_user_id_e6c454_idx'),
        ),
    ]
