# Generated by Django 6.0 on 2026-01-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='last_name',
        ),
        migrations.AddField(
            model_name='identity',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
