# Generated by Django 6.0 on 2026-01-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_identity_first_name_remove_identity_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
