# Generated by Django 6.0 on 2026-01-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_identity_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
