# Generated by Django 6.0 on 2026-01-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workspace_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='referrer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
