# Generated by Django 6.0 on 2026-03-07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_workspace_referrer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageBlob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[("db", "DB"), ("s3", "S3")],
                        max_length=20,
                    ),
                ),
                ("content_type", models.CharField(max_length=100)),
                ("byte_size", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("blob_data", models.BinaryField(blank=True, null=True)),
                ("object_key", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [models.Index(fields=["storage_backend", "created_at"], name="accounts_ima_storage_7c89a6_idx")],
            },
        ),
    ]
