# Generated by Django 6.0 on 2026-01-17 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_data', models.TextField(blank=True, null=True)),
                ('nonce', models.CharField(blank=True, max_length=512)),
                ('algorithm', models.CharField(choices=[('chacha20-poly1305', 'CHACHA20_POLY1305'), ('aes-256-gcm', 'AES_256_GCM')], default='chacha20-poly1305', max_length=50)),
                ('encryption_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_credentials', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('database_type', models.CharField(choices=[('postgres', 'POSTGRES'), ('mysql', 'MYSQL'), ('mssql', 'MSSQL'), ('oracle', 'ORACLE'), ('snowflake', 'SNOWFLAKE'), ('redshift', 'REDSHIFT'), ('bigquery', 'BIGQUERY')], max_length=20)),
                ('environment', models.CharField(blank=True, choices=[('production', 'PRODUCTION'), ('staging', 'STAGING'), ('testing', 'TESTING'), ('development', 'DEVELOPMENT')], help_text='Optional environment classification (production, staging, testing, development)', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('database_credential', models.ForeignKey(blank=True, help_text='Base credential for database connectivity (hostname, SSH config, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='connection.credential')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Account-specific permissions/restrictions')),
                ('access_level', models.CharField(choices=[('readonly', 'READONLY'), ('write', 'WRITE'), ('admin', 'ADMIN')], default='readonly', help_text='Access level classification (readonly, write, admin) - not enforced, for metadata/UI hints', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account_credential', models.ForeignKey(blank=True, help_text='Credential containing DB username/password for this account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='connection.credential')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='connection.database')),
            ],
        ),
        migrations.CreateModel(
            name='AccountHealthLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('success', models.BooleanField(help_text='True if connection succeeded, False if connectivity error')),
                ('error_message', models.TextField(blank=True, help_text='Error message if connection failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_health_logs', to='accounts.workspace')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='connection.database')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='connection.databaseaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('admin-set', 'ADMIN_SET'), ('requested', 'REQUESTED'), ('automatic', 'AUTOMATIC')], help_text='How this access was granted', max_length=20)),
                ('requested_at', models.DateTimeField(blank=True, help_text='When access was requested', null=True)),
                ('granted_at', models.DateTimeField(blank=True, help_text='When access was granted', null=True)),
                ('granted_until', models.DateTimeField(blank=True, help_text='Expiration time for temporary access', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When access was revoked', null=True)),
                ('reason', models.TextField(blank=True, help_text='User-provided reason for requesting access')),
                ('denied_at', models.DateTimeField(blank=True, help_text='When access request was denied', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('denied_by', models.ForeignKey(blank=True, help_text='User who denied this access request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denied_access', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(blank=True, help_text='User who granted this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_access', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Group with access (mutually exclusive with user)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_access', to='accounts.usergroup')),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who requested this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_access', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, help_text='User who revoked this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User with access (mutually exclusive with group)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_access', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Workspace this access grant belongs to (denormalized from account)', on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='accounts.workspace')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='connection.databaseaccount')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, help_text='Optional color for UI display (e.g., hex code)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_tags', to='accounts.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='database',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='databases', to='connection.databasetag'),
        ),
        migrations.CreateModel(
            name='UserKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('passphrase_hint', models.CharField(blank=True, help_text='First few words of passphrase to help user identify which key', max_length=100)),
                ('sample_payload', models.TextField(blank=True, help_text='Encrypted sample text to test passphrase')),
                ('sample_nonce', models.CharField(blank=True, help_text='Nonce for sample payload', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_keys', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_data', models.TextField(blank=True, null=True)),
                ('nonce', models.CharField(blank=True, max_length=512)),
                ('algorithm', models.CharField(choices=[('chacha20-poly1305', 'CHACHA20_POLY1305'), ('aes-256-gcm', 'AES_256_GCM')], default='chacha20-poly1305', max_length=50)),
                ('encrypted_key', models.TextField(blank=True, null=True)),
                ('key_nonce', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credentials', to='connection.credential')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credentials', to='connection.userkey')),
            ],
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['workspace', 'created_at'], name='connection__workspa_a8c1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='databaseaccount',
            index=models.Index(fields=['database', 'is_active'], name='connection__databas_d9434c_idx'),
        ),
        migrations.AddIndex(
            model_name='databaseaccount',
            index=models.Index(fields=['access_level'], name='connection__access__3d5ec6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='databaseaccount',
            unique_together={('database', 'name')},
        ),
        migrations.AddIndex(
            model_name='accounthealthlog',
            index=models.Index(fields=['account', 'created_at', 'success'], name='connection__account_7d311a_idx'),
        ),
        migrations.AddIndex(
            model_name='accounthealthlog',
            index=models.Index(fields=['database', 'created_at', 'success'], name='connection__databas_10e44e_idx'),
        ),
        migrations.AddIndex(
            model_name='accounthealthlog',
            index=models.Index(fields=['workspace', 'created_at'], name='connection__workspa_e1827c_idx'),
        ),
        migrations.AddIndex(
            model_name='access',
            index=models.Index(fields=['workspace', 'user', 'revoked_at'], name='connection__workspa_5a1521_idx'),
        ),
        migrations.AddIndex(
            model_name='access',
            index=models.Index(fields=['workspace', 'group', 'revoked_at'], name='connection__workspa_dcc9af_idx'),
        ),
        migrations.AddIndex(
            model_name='access',
            index=models.Index(fields=['account', 'revoked_at'], name='connection__account_d39d07_idx'),
        ),
        migrations.AddIndex(
            model_name='access',
            index=models.Index(fields=['granted_until'], name='connection__granted_f11984_idx'),
        ),
        migrations.AddConstraint(
            model_name='access',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('user__isnull', False)), models.Q(('group__isnull', False), ('user__isnull', True)), _connector='OR'), name='access_user_or_group_not_both'),
        ),
        migrations.AddIndex(
            model_name='databasetag',
            index=models.Index(fields=['workspace', 'name'], name='connection__workspa_34163a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='databasetag',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='database',
            index=models.Index(fields=['workspace', 'is_active'], name='connection__workspa_7c7cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='database',
            index=models.Index(fields=['database_type'], name='connection__databas_0c5cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='database',
            index=models.Index(fields=['environment'], name='connection__environ_3ce1a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='database',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='userkey',
            index=models.Index(fields=['workspace', 'user', 'revoked_at'], name='connection__workspa_3f1fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='userkey',
            index=models.Index(fields=['user', 'revoked_at'], name='connection__user_id_0a7cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='userkey',
            index=models.Index(fields=['approved_at'], name='connection__approve_3c68b7_idx'),
        ),
        migrations.AddIndex(
            model_name='userkey',
            index=models.Index(fields=['confirmed_at'], name='connection__confirm_897279_idx'),
        ),
        migrations.AddIndex(
            model_name='usercredential',
            index=models.Index(fields=['credential', 'user_key'], name='connection__credent_876030_idx'),
        ),
        migrations.AddIndex(
            model_name='usercredential',
            index=models.Index(fields=['user_key'], name='connection__user_ke_fa31dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercredential',
            unique_together={('credential', 'user_key')},
        ),
    ]
