# Generated by Django 6.0 on 2026-01-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='True for demo databases created via demo endpoints'),
        ),
    ]
