[pytest]
DJANGO_SETTINGS_MODULE = vaultsql.settings.dev
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --strict-markers -m "not integration"
testpaths = tests

markers =
    integration: marks tests as integration tests requiring live services (deselect with '-m "not integration"')






